### ISSUE TITLE
Should be G♯ at measure 37, shouldn't it ?

### ISSUE THREAD

**Issue by cthiebaud** [eantoranz/bwv#3]
![image](https://user-images.githubusercontent.com/773520/145541656-4e085cda-5068-467b-96c5-4ca2b52759da.png)

In the source, at measure 37, one reads :
"last g seems an oversight _but_ it's on the manuscript so..."

attached a detail screenshot of the manuscript (copied from here:http://www.preludiomusic.com/doc/prodotti/pdf/445-pls22714-ciaccona-bach-cherici-vis.pdf): 

There is no G♮ in the manuscript. Do I miss something?

**Comment by eantoranz** [comment]
Using `\accidentalStyle forget` (in the making in `forget`) branch, this problem will go away.

It could either be written

`\once\omit Accidental gis`

or

`g`

(Which will render no natural accidental because the previous gis will be forgotten).

Right now in the `forget` branch I am following the second way

https://github.com/eantoranz/bwv/blob/7965cb3a5f8c797110d05a203085ce77ef3e3c94/BWV%201004%20Violin%20Partita%20II%20D%20minor/5-ciaccona.ly#L268

but I wouldn't mind using the first one if anybody cares about it that much and is willing to send a patch for it.

Closing this ticket as it won't be necessary (once I merge `forget` branch).
